name = "saasingenieriaelectrica200417"
pages_build_output_dir = "frontend/dist"

[vars]
# Tus variables de entorno aquí
SECRET_KEY = "super_secret_jwt_key_please_change_me"

[[d1_databases]]
binding = "DB"
database_name = "saas-db"
database_id = "a1e4cb34-3203-4fd7-b6a2-8f228a3c0eb5"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "saasingenieriaelectrica200417"

[[kv_namespaces]]
binding = "KV_NAMESPACE"
id = "f60a9f62c8e342249e0b23081e7d44c8"

[site]
bucket = "./frontend/dist"
